server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mytest?useSSL=true
    username: root
    password: 123123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

wechat:
  appId: wxcff53b2cbf2535ea
  secret: 2e3345bf7fc8647ef50e3a7e3dde0de6

