spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mytest
    username: root
    password: 168168
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

wechat:
  appId: wxcff53b2cbf2535ea
  secret: 2e3345bf7fc8647ef50e3a7e3dde0de6